import Head from "next/head";
import CaroselContainer from "../components/ui/common/carosel/CaroselContainer";

export default function HomePage() {
  return (
    <div className="">
      <Head>
        <title>Picante</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen w-full bg-gray-100">
        <CaroselContainer />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {},
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 510, // In seconds
  };
}
